server:
  servlet:
    context-path: /starter
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/town?characterEncoding=UTF-8&&serverTimezone=GMT
    username: root
    password: root123456
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 10
      max-active: 20
      max-wait: 60000
      validation-query: SELECT 1
      test-on-borrow: true
      test-while-idle: true
      test-on-return: false
